% Accepts detected and aligned spikes generated by NSxFile and then
% uses UMS2K to further sort them. Saves each channel as its own file.

function RAR_spike_sort (input_file)

	MUA_data = importdata(input_file);

	[path, filename, ~] = fileparts(input_file);
	output_path = strcat (path, '/', filename, '/sorted_spikes/');
	mkdir(output_path);

	for c = 1:length(MUA_data)
		spikes = ss_kmeans(MUA_data(c));
		spikes = ss_energy(spikes);
		spikes = ss_aggregate(spikes);
		output_file = strcat (output_path, filename, '_sorted_channel_', num2str(spikes.info.channel), '.mat');
		save(output_file,'spikes');
	end

end